// Do not edit, this file was generated by github.com/newlix/core.
@file:Suppress("unused")
package com.example

import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import kotlinx.serialization.encodeToString
import kotlinx.serialization.json.Json
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import okhttp3.OkHttpClient
import okhttp3.Request
import okhttp3.RequestBody.Companion.toRequestBody

data class CoreError(
    val status: Int,
    val msg: String
) : Exception()

// TodoClient is the API client.
// url is the required API endpoint address.
class TodoClient(val endpoint: String) {
    private val json = Json { ignoreUnknownKeys = true }

    // AuthToken is an optional authentication token.
    var authToken: String? = null

    // client is used for making requests.
    val client = OkHttpClient()

    private suspend inline fun <reified Input, reified Output> call(
        method: String, input: Input
    ): Output {
        return withContext(Dispatchers.IO) {
            val url = "$endpoint/$method"
            val postBody = json.encodeToString(input)
            val request = Request.Builder()
                .url(url)
                .post(postBody.toRequestBody())
                .addHeader("Content-Type", "application/json")
            if (authToken != null) {
                request.addHeader("Authorization", "Bearer $authToken")
            }

            return@withContext client.newCall(request.build()).execute().use { response ->
                val body: String = response.body?.string() ?: ""
                if (!response.isSuccessful) {
                    throw CoreError(
                        status = response.code,
                        msg = body
                    )
                }
                return@use json.decodeFromString<Output>(body)
            }
        }
    }

    // AddItem adds an item to the list.
    suspend fun addItem(input: AddItemInput): AddItemOutput {
        return call("add_item", input)
    }

    // GetItems returns all items in the list.
    suspend fun getItems(input: GetItemsInput): GetItemsOutput {
        return call("get_items", input)
    }

    // RemoveItem removes an item from the to-do list.
    suspend fun removeItem(input: RemoveItemInput): RemoveItemOutput {
        return call("remove_item", input)
    }

}

@Serializable
data class AddItemInput(
    @SerialName("item") val item: Item = Item(),
)

@Serializable
class AddItemOutput(
)

@Serializable
class GetItemsInput(
)

@Serializable
data class GetItemsOutput(
    @SerialName("items") val items: List<Item> = emptyList(),
)

@Serializable
data class RemoveItemInput(
    @SerialName("id") val id: Long = 0,
)

@Serializable
data class RemoveItemOutput(
    @SerialName("item") val item: Item = Item(),
)

