// Do not edit, this file was generated by github.com/newlix/core.
package com.example



import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

// Item is a to-do item.
@Serializable
data class Item(
    @SerialName("id") val id: Int = 0,
    @SerialName("text") val text: String = "",
    @SerialName("created_at") val createdAt: Date = Date(),
)

