// Do not edit, this file was generated by github.com/newlix/core.
package todo

import "time"

// Item is a to-do item.
type Item struct {
	// ID is the unique id
	ID int `json:"id" db:"id"`

	// Tex is the content
	Text string `json:"text" db:"text"`

	// CreatedAt is the timestamp which the item created at
	CreatedAt time.Time `json:"created_at" db:"created_at"`
}
