// Do not edit, this file was generated by github.com/newlix/core.
package todo
import "encoding/json"
import "time"

func ptr[T any](x T) *T {
    return &x
}

// Item is a to-do item.
type Item struct {
	// ID is the unique id
	ID int `json:"id" db:"id"`

	// Tex is the content
	Text string `json:"text" db:"text"`

	// CreatedAt is the timestamp which the item created at
	CreatedAt *time.Time `json:"created_at" db:"created_at"`
}

func (p Item) MarshalJSON() ([]byte, error) {
	type Alias struct {
		ID int `json:"id" db:"id"`
		Text string `json:"text" db:"text"`
		CreatedAt int64 `json:"created_at" db:"created_at"`
	}
	return json.Marshal(&Alias{
		ID: p.ID,
		Text: p.Text,
		CreatedAt: p.CreatedAt.Unix(),
	})
}

func (p *Item) UnmarshalJSON(data []byte) error {
	type Alias struct {
		ID int `json:"id" db:"id"`
		Text string `json:"text" db:"text"`
		CreatedAt int64 `json:"created_at" db:"created_at"`
	}
	var tmp Alias
	if err := json.Unmarshal(data, &tmp); err != nil {
		return err
	}
	p.ID = tmp.ID
	p.Text = tmp.Text
	p.CreatedAt = ptr(time.Unix(tmp.CreatedAt, 0))
	return nil
}
