// Do not edit, this file was generated by github.com/newlix/core.
package database

import (
	"context"

	"github.com/newlix/core"
	"github.com/newlix/core/examples/todo"
)

const selectItemQuery = `SELECT "id", "text", "created_at" FROM "item" `

func SelectItem(ctx context.Context, q core.Querier, extraQuery string, args ...any) (todo.Item, error) {
	row := q.QueryRowContext(ctx, selectItemQuery+extraQuery, args...)
	var o todo.Item
	err := row.Scan(
		&o.ID,
		&o.Text,
		&o.CreatedAt,
	)
	return o, err
}

func SelectItems(ctx context.Context, q core.Querier, extraQuery string, args ...any) ([]todo.Item, error) {
	rows, err := q.QueryContext(ctx, selectItemQuery+extraQuery, args...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var objs []todo.Item
	for rows.Next() {
		var obj todo.Item
		if err := rows.Scan(
			&obj.ID,
			&obj.Text,
			&obj.CreatedAt,
		); err != nil {
			return nil, err
		}
		objs = append(objs, obj)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return objs, nil
}

func SelectItemWithID(ctx context.Context, q core.Querier, id string) (todo.Item, error) {
	return SelectItem(ctx, q, `WHERE "id" = $1`, id)
}

func SelectAllItems(ctx context.Context, q core.Querier) ([]todo.Item, error) {
	return SelectItems(ctx, q, "")
}

const insertItemQuery = `INSERT INTO "item" ("id", "text", "created_at") VALUES ($1, $2, $3);`

func InsertItem(ctx context.Context, q core.Querier, obj todo.Item) error {
	_, err := q.ExecContext(ctx, insertItemQuery,
		obj.ID,
		obj.Text,
		obj.CreatedAt,
	)
	return err
}

const updateItemQuery = `UPDATE "item"
SET "text" = $2, "created_at" = $3
WHERE id = $1;`

func UpdateItem(ctx context.Context, q core.Querier, obj todo.Item) error {
	_, err := q.ExecContext(ctx, updateItemQuery,
		obj.ID,
		obj.Text,
		obj.CreatedAt,
	)
	return err
}

const upsertItemQuery = `INSERT INTO "item" ("id", "text", "created_at") VALUES ($1, $2, $3)
ON CONFLICT ("id")
DO UPDATE SET "id" = $1, "text" = $2, "created_at" = $3;`

func UpsertItem(ctx context.Context, q core.Querier, obj todo.Item) error {
	_, err := q.ExecContext(ctx, upsertItemQuery,
		obj.ID,
		obj.Text,
		obj.CreatedAt,
	)
	return err
}

const deleteItemQuery = `DELETE FROM "item" WHERE "id" = $1;`

func DeleteItem(ctx context.Context, q core.Querier, id string) error {
	_, err := q.ExecContext(ctx, deleteItemQuery, id)
	return err
}
