-- Do not edit, this file was generated by github.com/newlix/core.

-- name: AddItem :exec
INSERT INTO item (id, text) VALUES (@id, @text);

-- name: GetItems :many
SELECT id, text FROM item;

-- name: RemoveItem :one
SELECT id, text FROM item;
