-- Do not edit, this file was generated by github.com/newlix/core.

-- name: AddItem :exec
INSERT INTO item (id, text, created_at) VALUES (@id, @text, @created_at);

-- name: GetItems :many
SELECT id, text, created_at FROM item;

-- name: RemoveItem :one
SELECT id, text, created_at FROM item;
