package sqlc_test

import (
	"bytes"
	"os"
	"testing"

	"github.com/google/go-cmp/cmp"
	"github.com/newlix/core"
	"github.com/newlix/core/examples/todo/spec"
	"github.com/newlix/core/generators/sqlc"
)

func TestGenerateQueries(t *testing.T) {
	b, err := os.ReadFile("testdata/todo_queries.sql")
	if err != nil {
		t.Fatal(err)
	}
	want := string(b)
	var buf bytes.Buffer
	if err := sqlc.GenerateQueries(&buf, spec.Methods, spec.Types); err != nil {
		t.Fatal(err)
	}
	got := buf.String()
	if got != want {
		t.Error(cmp.Diff(got, want))
	}
}

func TestGenerateQueries_NoInputsNoOutputs(t *testing.T) {
	methods, err := core.InitMethods(core.Method{
		Name:        "health_check",
		Description: "HealthCheck returns server status.",
	})
	if err != nil {
		t.Fatal(err)
	}
	var buf bytes.Buffer
	if err := sqlc.GenerateQueries(&buf, methods, nil); err != nil {
		t.Fatal(err)
	}
	got := buf.String()
	want := "-- Do not edit, this file was generated by github.com/newlix/core.\n\n" +
		"-- name: HealthCheck :exec\n"
	if got != want {
		t.Error(cmp.Diff(got, want))
	}
}

func TestGenerateQueries_AllBuiltinOutputs(t *testing.T) {
	types, err := core.InitTypes(core.Type{
		Name:        "product",
		Description: "Product is an item for sale.",
		Fields: []core.Field{
			{Name: "id", Description: "unique identifier", Type: core.Int},
			{Name: "name", Description: "product name", Type: core.String},
			{Name: "is_active", Description: "active flag", Type: core.Bool},
			{Name: "price", Description: "product price", Type: core.Float},
		},
	})
	if err != nil {
		t.Fatal(err)
	}
	methods, err := core.InitMethods(core.Method{
		Name:        "get_product",
		Description: "GetProduct returns a product.",
		Outputs: []core.Field{
			{Name: "product", Description: "the product", Type: types[0]},
		},
	})
	if err != nil {
		t.Fatal(err)
	}
	var buf bytes.Buffer
	if err := sqlc.GenerateQueries(&buf, methods, types); err != nil {
		t.Fatal(err)
	}
	got := buf.String()
	want := "-- Do not edit, this file was generated by github.com/newlix/core.\n\n" +
		"-- name: GetProduct :one\n" +
		"SELECT id, name, is_active, price FROM product;\n"
	if got != want {
		t.Error(cmp.Diff(got, want))
	}
}

func TestGenerateQueries_ArrayOutputs(t *testing.T) {
	types, err := core.InitTypes(core.Type{
		Name:        "product",
		Description: "Product is an item for sale.",
		Fields: []core.Field{
			{Name: "id", Description: "unique identifier", Type: core.Int},
			{Name: "name", Description: "product name", Type: core.String},
		},
	})
	if err != nil {
		t.Fatal(err)
	}
	methods, err := core.InitMethods(core.Method{
		Name:        "list_products",
		Description: "ListProducts returns all products.",
		Outputs: []core.Field{
			{Name: "products", Description: "all products", Type: types[0], IsArray: true},
		},
	})
	if err != nil {
		t.Fatal(err)
	}
	var buf bytes.Buffer
	if err := sqlc.GenerateQueries(&buf, methods, types); err != nil {
		t.Fatal(err)
	}
	got := buf.String()
	want := "-- Do not edit, this file was generated by github.com/newlix/core.\n\n" +
		"-- name: ListProducts :many\n" +
		"SELECT id, name FROM product;\n"
	if got != want {
		t.Error(cmp.Diff(got, want))
	}
}

func TestGenerateQueries_InsertAllBuiltinTypes(t *testing.T) {
	types, err := core.InitTypes(core.Type{
		Name:        "product",
		Description: "Product is an item for sale.",
		Fields: []core.Field{
			{Name: "id", Description: "unique identifier", Type: core.Int},
			{Name: "name", Description: "product name", Type: core.String},
			{Name: "is_active", Description: "active flag", Type: core.Bool},
			{Name: "price", Description: "product price", Type: core.Float},
		},
	})
	if err != nil {
		t.Fatal(err)
	}
	methods, err := core.InitMethods(core.Method{
		Name:        "create_product",
		Description: "CreateProduct creates a product.",
		Inputs: []core.Field{
			{Name: "product", Description: "the product", Type: types[0]},
		},
	})
	if err != nil {
		t.Fatal(err)
	}
	var buf bytes.Buffer
	if err := sqlc.GenerateQueries(&buf, methods, types); err != nil {
		t.Fatal(err)
	}
	got := buf.String()
	want := "-- Do not edit, this file was generated by github.com/newlix/core.\n\n" +
		"-- name: CreateProduct :exec\n" +
		"INSERT INTO product (id, name, is_active, price) VALUES (@id, @name, @is_active, @price);\n"
	if got != want {
		t.Error(cmp.Diff(got, want))
	}
}
