package sqlc_test

import (
	"bytes"
	"os"
	"testing"

	"github.com/google/go-cmp/cmp"
	"github.com/newlix/core"
	"github.com/newlix/core/examples/todo/spec"
	"github.com/newlix/core/generators/sqlc"
)

func TestGenerateSchema(t *testing.T) {
	b, err := os.ReadFile("testdata/todo_schema.sql")
	if err != nil {
		t.Fatal(err)
	}
	want := string(b)
	var buf bytes.Buffer
	if err := sqlc.GenerateSchema(&buf, spec.Types); err != nil {
		t.Fatal(err)
	}
	got := buf.String()
	if got != want {
		t.Error(cmp.Diff(got, want))
	}
}

func TestGenerateSchema_AllBuiltinTypes(t *testing.T) {
	types, err := core.InitTypes(core.Type{
		Name:        "product",
		Description: "Product is an item for sale.",
		Fields: []core.Field{
			{Name: "id", Description: "unique identifier", Type: core.Int},
			{Name: "name", Description: "product name", Type: core.String},
			{Name: "is_active", Description: "active flag", Type: core.Bool},
			{Name: "price", Description: "product price", Type: core.Float},
		},
	})
	if err != nil {
		t.Fatal(err)
	}
	var buf bytes.Buffer
	if err := sqlc.GenerateSchema(&buf, types); err != nil {
		t.Fatal(err)
	}
	got := buf.String()
	want := "-- Do not edit, this file was generated by github.com/newlix/core.\n\n" +
		"CREATE TABLE product (\n" +
		"    id BIGINT PRIMARY KEY NOT NULL,\n" +
		"    name TEXT NOT NULL,\n" +
		"    is_active BOOLEAN NOT NULL,\n" +
		"    price DOUBLE PRECISION NOT NULL\n" +
		");\n"
	if got != want {
		t.Error(cmp.Diff(got, want))
	}
}

func TestGenerateSchema_EmptyFields(t *testing.T) {
	types, err := core.InitTypes(core.Type{
		Name:        "empty",
		Description: "Empty has no fields.",
	})
	if err != nil {
		t.Fatal(err)
	}
	var buf bytes.Buffer
	if err := sqlc.GenerateSchema(&buf, types); err != nil {
		t.Fatal(err)
	}
	got := buf.String()
	want := "-- Do not edit, this file was generated by github.com/newlix/core.\n\n"
	if got != want {
		t.Error(cmp.Diff(got, want))
	}
}

func TestGenerateSchema_MultipleTypes(t *testing.T) {
	types, err := core.InitTypes(
		core.Type{
			Name:        "product",
			Description: "Product is an item for sale.",
			Fields: []core.Field{
				{Name: "id", Description: "unique identifier", Type: core.Int},
				{Name: "name", Description: "product name", Type: core.String},
			},
		},
		core.Type{
			Name:        "tag",
			Description: "Tag is a label.",
			Fields: []core.Field{
				{Name: "id", Description: "tag id", Type: core.Int},
				{Name: "label", Description: "tag label", Type: core.String},
				{Name: "is_active", Description: "active flag", Type: core.Bool},
			},
		},
	)
	if err != nil {
		t.Fatal(err)
	}
	var buf bytes.Buffer
	if err := sqlc.GenerateSchema(&buf, types); err != nil {
		t.Fatal(err)
	}
	got := buf.String()
	want := "-- Do not edit, this file was generated by github.com/newlix/core.\n\n" +
		"CREATE TABLE product (\n" +
		"    id BIGINT PRIMARY KEY NOT NULL,\n" +
		"    name TEXT NOT NULL\n" +
		");\n\n" +
		"CREATE TABLE tag (\n" +
		"    id BIGINT PRIMARY KEY NOT NULL,\n" +
		"    label TEXT NOT NULL,\n" +
		"    is_active BOOLEAN NOT NULL\n" +
		");\n"
	if got != want {
		t.Error(cmp.Diff(got, want))
	}
}
