package sqlc

import (
	"io"
	"log"
	"os"
	"path"
	"strings"

	"github.com/newlix/core"
)

type GenerateSchemaFileConfig struct {
	Output string
	Types  []core.Type
}

func GenerateSchemaFile(c GenerateSchemaFileConfig) {
	os.MkdirAll(path.Dir(c.Output), 0o700)
	w, err := os.Create(c.Output)
	if err != nil {
		log.Fatal(err)
	}
	defer w.Close()

	GenerateSchema(w, c.Types)
}

func generateWarning(w io.Writer) {
	out(w, "-- Do not edit, this file was generated by github.com/newlix/core.")
	out(w, "")
}

func GenerateSchema(w io.Writer, tt []core.Type) {
	generateWarning(w)
	for i, t := range tt {
		ff := core.BuiltinTypeFields(t.Fields)
		if len(ff) == 0 {
			continue
		}
		out(w, "CREATE TABLE %s (", t.Name)
		for j, f := range ff {
			col := "    " + f.Name + " " + sqlcType(f)
			if isPrimaryKey(f.Name, t.PrimaryKey) {
				col += " PRIMARY KEY"
			}
			if !strings.HasPrefix(f.Type.GoType, "*") {
				col += " NOT NULL"
			}
			if j < len(ff)-1 {
				col += ","
			}
			out(w, "%s", col)
		}
		out(w, ");")
		if i < len(tt)-1 {
			out(w, "")
		}
	}
}

func isPrimaryKey(name string, pk []string) bool {
	for _, k := range pk {
		if k == name {
			return true
		}
	}
	return false
}

func sqlcType(f core.Field) string {
	t := f.Type.SqlcType
	if t == "" {
		log.Fatalf("missing SqlcType for %q", f.Type.Name)
	}
	return t
}
