package sqlc

import (
	"fmt"
	"io"
	"strings"

	"github.com/newlix/core"
	"github.com/newlix/core/generators/common"
)

type GenerateSchemaFileConfig struct {
	Output string
	Types  []core.Type
}

func GenerateSchemaFile(c GenerateSchemaFileConfig) error {
	return common.GenerateFile(c.Output, func(w io.Writer) error {
		return GenerateSchema(w, c.Types)
	})
}

func generateWarning(w io.Writer) {
	out(w, "-- Do not edit, this file was generated by github.com/newlix/core.")
	out(w, "")
}

func GenerateSchema(w io.Writer, tt []core.Type) error {
	generateWarning(w)
	first := true
	for _, t := range tt {
		ff := core.BuiltinTypeFields(t.Fields)
		if len(ff) == 0 {
			continue
		}
		if !first {
			out(w, "")
		}
		first = false
		out(w, "CREATE TABLE %s (", t.Name)
		for j, f := range ff {
			typ, err := sqlcType(f)
			if err != nil {
				return err
			}
			col := "    " + f.Name + " " + typ
			if isPrimaryKey(f.Name, t.PrimaryKey) {
				col += " PRIMARY KEY"
			}
			if !strings.HasPrefix(f.Type.GoType, "*") {
				col += " NOT NULL"
			}
			if j < len(ff)-1 {
				col += ","
			}
			out(w, "%s", col)
		}
		out(w, ");")
	}
	return nil
}

func isPrimaryKey(name string, pk []string) bool {
	for _, k := range pk {
		if k == name {
			return true
		}
	}
	return false
}

func sqlcType(f core.Field) (string, error) {
	t := f.Type.SqlcType
	if t == "" {
		return "", fmt.Errorf("missing SqlcType for %q", f.Type.Name)
	}
	return t, nil
}
